"""core data model

Revision ID: 0002_core_data_model
Revises: 0001_initial_users
Create Date: 2026-05-16 23:32:55.466912

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "0002_core_data_model"
down_revision: str | None = "0001_initial_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_config_key"), "app_config", ["key"], unique=True)
    op.create_table(
        "company_reference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("sector", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("industry", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
        sa.Column("isin", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("corp_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("source_payload", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange", "symbol", name="uq_company_reference_exchange_symbol"),
    )
    op.create_index(
        op.f("ix_company_reference_company_name"),
        "company_reference",
        ["company_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_company_reference_country"), "company_reference", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_company_reference_exchange"), "company_reference", ["exchange"], unique=False
    )
    op.create_index(
        op.f("ix_company_reference_symbol"), "company_reference", ["symbol"], unique=False
    )
    op.create_table(
        "source_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_runs_source_name"), "source_runs", ["source_name"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("source_event_id", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("company_reference_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("event_date", sa.DateTime(), nullable=True),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_reference_id"],
            ["company_reference.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_company_reference_id"), "events", ["company_reference_id"], unique=False
    )
    op.create_index(op.f("ix_events_dedup_key"), "events", ["dedup_key"], unique=True)
    op.create_index(op.f("ix_events_event_date"), "events", ["event_date"], unique=False)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_source_event_id"), "events", ["source_event_id"], unique=True)
    op.create_index(op.f("ix_events_source_name"), "events", ["source_name"], unique=False)
    op.create_index(op.f("ix_events_symbol"), "events", ["symbol"], unique=False)
    op.create_table(
        "raw_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("schema_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("source_event_id", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["source_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raw_items_dedup_key"), "raw_items", ["dedup_key"], unique=False)
    op.create_index(
        op.f("ix_raw_items_source_event_id"), "raw_items", ["source_event_id"], unique=False
    )
    op.create_index(op.f("ix_raw_items_source_name"), "raw_items", ["source_name"], unique=False)
    op.create_index(
        op.f("ix_raw_items_source_run_id"), "raw_items", ["source_run_id"], unique=False
    )
    op.create_table(
        "telegram_chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("chat_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_telegram_chats_chat_id"), "telegram_chats", ["chat_id"], unique=True)
    op.create_index(
        op.f("ix_telegram_chats_is_active"), "telegram_chats", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_telegram_chats_user_id"), "telegram_chats", ["user_id"], unique=False)
    op.create_table(
        "tracked_companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_reference_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("sector", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("themes", sa.JSON(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("source_payload", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_reference_id"],
            ["company_reference.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange", "symbol", name="uq_tracked_companies_exchange_symbol"),
    )
    op.create_index(
        op.f("ix_tracked_companies_company_reference_id"),
        "tracked_companies",
        ["company_reference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_companies_exchange"), "tracked_companies", ["exchange"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_companies_is_active"), "tracked_companies", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_tracked_companies_symbol"), "tracked_companies", ["symbol"], unique=False
    )
    op.create_table(
        "classifier_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_item_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("response_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("is_company_critical", sa.Boolean(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_item_id"],
            ["raw_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classifier_runs_event_id"), "classifier_runs", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_classifier_runs_is_company_critical"),
        "classifier_runs",
        ["is_company_critical"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classifier_runs_raw_item_id"), "classifier_runs", ["raw_item_id"], unique=False
    )
    op.create_table(
        "event_relevance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("tracked_company_id", sa.Integer(), nullable=True),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tracked_company_id"],
            ["tracked_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_relevance_event_id"), "event_relevance", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_relevance_matched"), "event_relevance", ["matched"], unique=False
    )
    op.create_index(
        op.f("ix_event_relevance_tracked_company_id"),
        "event_relevance",
        ["tracked_company_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("dedup_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("reminder_window", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("skip_reason", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_dedup_key"), "notifications", ["dedup_key"], unique=True)
    op.create_index(op.f("ix_notifications_event_id"), "notifications", ["event_id"], unique=False)
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_event_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_dedup_key"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_event_relevance_tracked_company_id"), table_name="event_relevance")
    op.drop_index(op.f("ix_event_relevance_matched"), table_name="event_relevance")
    op.drop_index(op.f("ix_event_relevance_event_id"), table_name="event_relevance")
    op.drop_table("event_relevance")
    op.drop_index(op.f("ix_classifier_runs_raw_item_id"), table_name="classifier_runs")
    op.drop_index(op.f("ix_classifier_runs_is_company_critical"), table_name="classifier_runs")
    op.drop_index(op.f("ix_classifier_runs_event_id"), table_name="classifier_runs")
    op.drop_table("classifier_runs")
    op.drop_index(op.f("ix_tracked_companies_symbol"), table_name="tracked_companies")
    op.drop_index(op.f("ix_tracked_companies_is_active"), table_name="tracked_companies")
    op.drop_index(op.f("ix_tracked_companies_exchange"), table_name="tracked_companies")
    op.drop_index(op.f("ix_tracked_companies_company_reference_id"), table_name="tracked_companies")
    op.drop_table("tracked_companies")
    op.drop_index(op.f("ix_telegram_chats_user_id"), table_name="telegram_chats")
    op.drop_index(op.f("ix_telegram_chats_is_active"), table_name="telegram_chats")
    op.drop_index(op.f("ix_telegram_chats_chat_id"), table_name="telegram_chats")
    op.drop_table("telegram_chats")
    op.drop_index(op.f("ix_raw_items_source_run_id"), table_name="raw_items")
    op.drop_index(op.f("ix_raw_items_source_name"), table_name="raw_items")
    op.drop_index(op.f("ix_raw_items_source_event_id"), table_name="raw_items")
    op.drop_index(op.f("ix_raw_items_dedup_key"), table_name="raw_items")
    op.drop_table("raw_items")
    op.drop_index(op.f("ix_events_symbol"), table_name="events")
    op.drop_index(op.f("ix_events_source_name"), table_name="events")
    op.drop_index(op.f("ix_events_source_event_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_event_date"), table_name="events")
    op.drop_index(op.f("ix_events_dedup_key"), table_name="events")
    op.drop_index(op.f("ix_events_company_reference_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_source_runs_source_name"), table_name="source_runs")
    op.drop_table("source_runs")
    op.drop_index(op.f("ix_company_reference_symbol"), table_name="company_reference")
    op.drop_index(op.f("ix_company_reference_exchange"), table_name="company_reference")
    op.drop_index(op.f("ix_company_reference_country"), table_name="company_reference")
    op.drop_index(op.f("ix_company_reference_company_name"), table_name="company_reference")
    op.drop_table("company_reference")
    op.drop_index(op.f("ix_app_config_key"), table_name="app_config")
    op.drop_table("app_config")
    # ### end Alembic commands ###
