"""Pydantic response models for every OpenAI Responses-API call site.

Single source of truth: each Structured Outputs call passes one of these
classes to ``client.responses.parse(text_format=...)``. The SDK derives
the JSON Schema, sets ``strict: true``, sends the request, then returns
a typed instance on ``response.output_parsed``.

Why centralized here instead of inline next to each service: the schemas
ARE the contract between the LLM and the rest of the pipeline. Keeping
them together makes it obvious when two call sites need to share a
field (Source, CitedSource), and a future schema-versioning sweep has
one place to look. Hand-rolled JSON Schema dicts previously lived in
every service module and drifted independently — that's the bug class
this layout removes.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

# ── Canonical enums ──────────────────────────────────────────────────────

# Closed enum of catalyst event subtypes. The classifier had been emitting
# free-form strings (21 distinct subtype labels in prod for ~15 canonical
# categories), which fragmented dedup. Strict mode + this enum forces
# canonical labels. Keep "earnings_report" and "guidance" spelled exactly —
# catalyst_enrich._ENRICH_SUBTYPES gates earnings enrichment on those two
# strings.
EventSubtype = Literal[
    "earnings_report",
    "guidance",
    "product_launch",
    "manufacturing_expansion",
    "partnership",
    "m_and_a",
    "regulatory_decision",
    "lockup_unlock",
    "uplisting",
    "management_change",
    "financing",
    "analyst_action",
    "index_inclusion",
    "investor_day",
    "other",
]

Importance = Literal["low", "medium", "high"]
SuggestedAction = Literal["ignore", "watch", "research", "act"]
BeatOrMiss = Literal["beat", "miss", "inline", "unknown"]
SourceKind = Literal["rss", "ir_press", "blog", "sec", "hkex", "twitter"]


# OpenAI strict mode requires `additionalProperties: false`. Pydantic
# emits that for `extra="forbid"`. Apply it everywhere via this base so
# we cannot accidentally ship a schema with `additionalProperties: true`.
class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


# ── Shared inner objects ─────────────────────────────────────────────────


class CitedSource(_StrictModel):
    """A single reputable source the LLM consulted. Both fields required
    so the renderer can always show {name -> URL}."""

    name: str
    url: str


# ── Catalyst classifier (openai_classifier.classify) ─────────────────────


class CatalystClassification(_StrictModel):
    """Per-headline classification output. The classifier is the upstream
    decision point — its subtype label feeds dedup, its importance and
    confidence feed the autosend gate, its summary feeds the alert body.

    ``ignore_reason`` and ``story_key`` are always present (empty string
    when not applicable). strict-mode does not allow nullable string
    fields unless we declare them so explicitly — keeping these as
    ``str`` sidesteps that without losing information."""

    is_company_critical: bool
    event_subtype: EventSubtype
    importance: Importance
    confidence: float = Field(ge=0, le=1)
    expected_impact: str
    summary: str
    why_it_matters: str
    suggested_action: SuggestedAction
    ignore_reason: str
    # Canonical event identifier for cross-language / cross-paraphrase
    # dedup. Generated by the LLM under tight format rules (see the
    # `_SYSTEM` prompt). Two articles about the same underlying event
    # must collapse to the same key regardless of source language.
    # Empty string for non-catalyst items (is_company_critical=false).
    story_key: str


# ── Semantic same-event judge (openai_classifier.same_event) ─────────────


class SameEventJudgement(_StrictModel):
    """The dedup grey-zone judge's verdict — boolean only. Used by
    catalyst_classify._find_semantic_twin when title similarity is between
    grey_threshold and title_threshold."""

    same: bool


# ── Earnings-report extraction (earnings_enrich.extract_from_url) ────────


class EarningsExtraction(_StrictModel):
    """Structured financials pulled from a single quarterly report PDF/HTML.

    Numeric fields are nullable because the document may not state every
    line item (e.g. some HK reports omit YoY %, some US presses omit
    gross profit). ``currency`` carries the unit string — "USD", "NT$
    thousands", etc. ``headline`` is the one-liner the alert renders.
    """

    period_label: str
    currency: str
    revenue: float | None
    revenue_yoy_pct: float | None
    gross_profit: float | None
    gross_margin_pct: float | None
    operating_profit: float | None
    net_profit: float | None
    net_profit_yoy_pct: float | None
    eps: float | None
    eps_yoy_pct: float | None
    beat_or_miss: BeatOrMiss
    guidance_change: str
    key_drivers: list[str]
    headline: str


# ── Analyst consensus search (earnings_enrich.find_consensus) ────────────


class ConsensusSearch(_StrictModel):
    """Analyst-consensus forecasts for a reporting period, captured via
    web_search. Numeric fields nullable — "we looked and found nothing
    reputable" is a valid outcome for thinly-covered names. ``sources``
    is what the alert cites so the trader can verify."""

    revenue: float | None
    eps: float | None
    net_profit: float | None
    currency: str
    period_label: str
    sources: list[CitedSource]
    notes: str


# ── IPO summarizer (filing-derived path) ─────────────────────────────────


class IpoSummaryOutput(_StrictModel):
    """Business description + implied market cap from a prospectus
    excerpt. ``description`` is the empty string when the excerpt is not
    actually a business overview (table of contents, image-only page)."""

    description: str
    market_cap_usd: float | None


# ── IPO summarizer (web_search fallback path) ────────────────────────────


class IpoWebDescriptionOutput(_StrictModel):
    """Business description from web_search, used when the prospectus
    path returned an empty description. ``sources`` cites the reputable
    sources consulted."""

    description: str
    sources: list[CitedSource]


# ── Web-search catalyst news adapter (websearch_news.fetch) ──────────────


class WebSearchNewsItem(_StrictModel):
    """A single news item returned by the catalyst web_search adapter.
    ``published_date`` is YYYY-MM-DD or None when the source does not
    state it — adapter normalizes the date downstream."""

    title: str
    url: str
    published_date: str | None
    summary: str


class WebSearchNewsOutput(_StrictModel):
    items: list[WebSearchNewsItem]


# ── Company-sources discovery (source_discovery.discover) ────────────────


class DiscoveredSourceItem(_StrictModel):
    """One canonical primary-source feed/page discovered for a tracked
    company (the company's IR press feed, a product blog, etc.).
    ``kind`` is a closed enum — anything else used to be silently
    dropped by the coercion layer."""

    kind: SourceKind
    url: str
    label: str
    confidence: float = Field(ge=0, le=1)
    reasoning: str


class SourceDiscoveryOutput(_StrictModel):
    sources: list[DiscoveredSourceItem]


# ── Entity preflight (entity_preflight.preflight) ────────────────────────

RelationshipKind = Literal["parent_of", "joint_venture", "major_shareholder"]


class EntityRef(_StrictModel):
    """A related entity surfaced by preflight. ``ticker`` and ``exchange``
    are the LLM's best guess of the primary listing — empty strings when
    private, defunct, or unknown (we still create the entity and let the
    user fill in listings later).

    ``confidence`` is bounded [0, 1] which also rejects NaN/Inf at the
    pydantic-validation boundary (NaN comparisons against 0/1 are False).
    That matters because the dict is later dumped into a Postgres JSON
    column via asyncpg, which rejects non-finite floats."""

    canonical_name: str
    country: str
    ticker: str
    exchange: str
    summary: str
    confidence: float = Field(ge=0, le=1)

    @field_validator("ticker", mode="before")
    @classmethod
    def _strip_dollar(cls, v: str) -> str:
        # The preflight system prompt tells the LLM to prefix tickers
        # with "$" in free-text fields and the model sometimes leaks
        # that prefix into the structured ticker too ("$2317" instead
        # of "2317"). Strip it at the schema boundary so every
        # downstream consumer — the auto-track lookup, the alert
        # formatter, the frontend display — sees a bare symbol.
        if v is None:
            return ""
        return str(v).strip().lstrip("$").strip()


class EntityPreflightOutput(_StrictModel):
    """Result of the preflight call when the user adds a tracked company.
    ``entity`` describes the tracked company's own issuer; the three
    list fields enumerate the relationships the LLM identified (each
    capped at a sensible upstream count via the prompt). ``sources``
    cites the URLs the model consulted."""

    entity: EntityRef
    parents: list[EntityRef]
    joint_venture_partners: list[EntityRef]
    major_shareholders: list[EntityRef]
    sources: list[CitedSource]
    notes: str


# ── Affected-companies assessment (affected_companies.assess) ────────────


class AffectedCompanyAssessment(_StrictModel):
    """LLM verdict on whether a single candidate company is materially
    impacted by a specific catalyst event. ``entity_ref`` echoes the
    candidate identifier we sent so we can join the result back. When
    ``include=False``, ``importance`` is "low" and ``reason`` is the
    one-line rationale for excluding it (kept for audit, not rendered)."""

    entity_ref: str
    include: bool
    importance: Importance
    reason: str


class AffectedCompaniesOutput(_StrictModel):
    assessments: list[AffectedCompanyAssessment]
